WINDOW = 20  # Trading days for volatility window (1 month)
STEP = 5

ASSETS = ["NIFTY", "GOLD", "USDINR", "CRUDE", "GSEC10Y"]

TARGET_ASSET = "NIFTY"
HEDGE_ASSETS = ["GOLD", "USDINR", "CRUDE", "GSEC10Y"]

DCC_A = 0.02
DCC_B = 0.95

# Risk and hedge controls
RIDGE_LAMBDA = 1e-4
MAX_HEDGE_WEIGHT = 1.10
EWMA_LAMBDA = 0.94
VOL_TARGET = 0.007

# Industry-style implementation controls
WEIGHT_SMOOTHING_ALPHA = 0.35
MIN_CORRELATION_CONFIDENCE = 0.05
MAX_GROSS_EXPOSURE = 1.75
TRANSACTION_COST_BPS = 2.0
SENTIMENT_STRENGTH = 0.20

# Defensive allocation controls (for investor-facing stability)
SAFE_ASSET = "GSEC10Y"
MIN_SAFE_ALLOCATION = 0.05
MAX_SAFE_ALLOCATION = 0.55
MOMENTUM_LOOKBACK = 20
DRAWDOWN_LOOKBACK = 60
DRAWDOWN_THRESHOLD = -0.08
