WINDOW = 20  # Trading days for volatility window (1 month)
STEP = 5

ASSETS = ["NIFTY", "GOLD", "USDINR", "CRUDE", "GSEC10Y"]

TARGET_ASSET = "NIFTY"
HEDGE_ASSETS = ["GOLD", "USDINR", "CRUDE", "GSEC10Y"]

DCC_A = 0.02
DCC_B = 0.95

# Risk and hedge controls
RIDGE_LAMBDA = 1e-4
MAX_HEDGE_WEIGHT = 1.10
EWMA_LAMBDA = 0.94
VOL_TARGET = 0.007

# Industry-style implementation controls
WEIGHT_SMOOTHING_ALPHA = 0.35
MIN_CORRELATION_CONFIDENCE = 0.05
MAX_GROSS_EXPOSURE = 1.75
TRANSACTION_COST_BPS = 2.0
SENTIMENT_STRENGTH = 0.20

# Defensive allocation controls (for investor-facing stability)
SAFE_ASSET = "GSEC10Y"
MIN_SAFE_ALLOCATION = 0.05
MAX_SAFE_ALLOCATION = 0.55
MOMENTUM_LOOKBACK = 20
DRAWDOWN_LOOKBACK = 60
DRAWDOWN_THRESHOLD = -0.08

# Hedge quality and implementation robustness
HEDGE_SHRINKAGE = 0.65
CORRELATION_FLOOR = 0.08
NO_TRADE_BAND = 0.025
STABILITY_LOOKBACK = 40

# Statistical validation
BOOTSTRAP_SAMPLES = 2000
RANDOM_SEED = 42


# Regime-switching DCC controls
REGIME_METHOD = "vol_threshold"
REGIME_LOOKBACK = 30
REGIME_VOL_MULTIPLIER = 1.15
REGIME_MIN_OBS = 12
DCC_A_CALM = 0.02
DCC_B_CALM = 0.96
DCC_A_STRESS = 0.05
DCC_B_STRESS = 0.90
STRESS_GROSS_EXPOSURE_MULT = 0.70
STRESS_HEDGE_SHRINKAGE_MULT = 1.10

# Concentration and sentiment-signal safeguards
MAX_SINGLE_HEDGE_ALLOCATION = 0.55
MIN_SENTIMENT_STD = 0.05
SENTIMENT_PROXY_STRENGTH = 0.30

# Sentiment-to-asset transmission and diversification
SENTIMENT_LOOKBACK_DAYS = 120
SENTIMENT_EWMA_SPAN = 7
ASSET_SENTIMENT_BETA = {
    "GOLD": 0.60,
    "USDINR": 0.35,
    "CRUDE": -0.70,
    "GSEC10Y": 0.45,
}
SENTIMENT_CROSS_SECTIONAL_STRENGTH = 0.30
DIVERSIFICATION_BLEND = 0.35
